#source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '8.0'
#xcodeproj 'Joystick Memory.xcodeproj'

def shared_pods
platform :ios, '8.0'
# Uncomment this line if you're using Swift or would like to use dynamic frameworks
#use_frameworks!

    pod 'GoogleAnalytics'
    #pod 'Facebook-iOS-SDK'
    #pod 'Parse'
    pod 'AFNetworking', '1.3.3'

    pod 'Reachability'
    pod 'NSString-HTML'
    pod 'NYXImagesKit'
    #pod 'SVProgressHUD'
    pod 'SIAlertView'

    pod 'SDWebImage'
    pod 'UIActivityIndicator-for-SDWebImage'
    #pod 'FlurrySDK'
    pod 'SoundManager'
    pod 'STSpriteKit'

    pod 'CJImageMerge'

    pod 'libextobjc'


end

target 'Joystick Memory' do
shared_pods
end


